### PR TITLE
Part 4

### PR DESCRIPTION
**Pull request by pingdori**
李蕙萍
http://54.243.128.73:3000/
http://54.243.128.73:3000/attraction/7

### CODE REVIEW

**Comment by cwpeng** [comment]
Cannot connect to your server.

**Comment by pingdori** [comment]
I have fix the server.
Could you please help to review mine work.

**Comment by cwpeng** [comment]
Layout of attraction.html is broken.

未命名-2

**Comment by pingdori** [comment]
I have fixed the issues.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
