### PR TITLE
Guide-Part0 and Part 1

### PR DESCRIPTION
**Pull request by pingdori**
老師您好 我是李蕙萍

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online URLs for testing.

**Comment by pingdori** [comment]
URLs for testing：

http://54.243.128.73:3000/api/attractions?page=1
http://54.243.128.73:3000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89
http://54.243.128.73:3000/api/attractions/5

**Comment by cwpeng** [comment]
1. "images" field should be an array containing image URLs separately, not a single string.
2. response format of http://54.243.128.73:3000/api/attractions/5 is incorrect, check API spec carefully.

Fix issues and leave comment for me to review again.

**Comment by pingdori** [comment]
I have fixed the issues.

**Comment by cwpeng** [comment]
1. I don't see any changes.
2. OK.

**Comment by pingdori** [comment]
Ok, I have fixed the issues.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
